name: Compile Markdown

on:
  push:
    branches: [ view ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm install -g remark-cli remark-html
      - run: remark *.md --use remark-html --output
      - name: Commit & Push Generated Data
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Actions Auto Build"
          find . ! -iname "*.html" -not -path "./.git/*" -not -name ".git" -delete
          git add -f .
          git commit -m "generate html files" || true
          git push --force origin HEAD:refs/heads/gh-pages
