name: Fix links

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: node fix-links.js
      - name: Commit & Push Generated Data
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Actions Auto Build"
          git pull origin view --ff-only
          git add -f *.md
          git commit -m "auto fix links" || true
          git push --force origin HEAD:refs/heads/view
